---
dist: xenial
language: go

go:
  - 1.12.x

env:
  - GO111MODULE=on

script:
  - make

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
